export const prototypeTokens = {
  source: "qhds-reference-css-snapshot",
  selectedPalette: "qld-health",
  color: {
    primitive: {
      accent: "#84d3ff",
      darkBackground: "#005eb8",
      darkBackgroundAlt: "#001d74",
      darkFocus: "#c6ffff",
      darkModeBackground: "#000053",
      darkVisitedLink: "#ffffff",
      heading: "#000053",
      lightBackground: "#e6f6ff",
      lightBackgroundAlt: "#e3e7ea",
      lightFocus: "#002e85",
      link: "#005eb8",
      neutral50: "#f5f5f5",
      neutral100: "#ebebeb",
      text: "#353535",
      textLighter: "#636363",
      white: "#ffffff"
    },
    qldVariables: [
      "--QLD-color-light__heading",
      "--QLD-color-light__text",
      "--QLD-color-light__link",
      "--QLD-color-light__focus",
      "--QLD-color-light__background",
      "--QLD-color-light__background--alt",
      "--QLD-color-dark__background",
      "--QLD-color-dark__background--alt",
      "--QLD-color-dark__focus",
      "--QLD-underline__thickness-thin",
      "--QLD-underline__thickness-thick",
      "--QLD-underline__offset"
    ],
    semanticVariables: [
      "--ssq-color-background",
      "--ssq-color-surface",
      "--ssq-color-surface-alt",
      "--ssq-color-heading",
      "--ssq-color-text",
      "--ssq-color-muted",
      "--ssq-color-border",
      "--ssq-color-border-strong",
      "--ssq-color-action",
      "--ssq-color-action-text",
      "--ssq-color-link",
      "--ssq-color-link-visited",
      "--ssq-color-link-decoration",
      "--ssq-color-error",
      "--ssq-color-error-border",
      "--ssq-color-error-background",
      "--ssq-color-invalid-border",
      "--ssq-color-focus",
      "--ssq-color-header-accent",
      "--ssq-color-header-background",
      "--ssq-color-header-text",
      "--ssq-color-left-nav-background",
      "--ssq-color-left-nav-border",
      "--ssq-color-info-background",
      "--ssq-color-info-border",
      "--ssq-color-info-text",
      "--ssq-color-success-background",
      "--ssq-color-success-border",
      "--ssq-color-success-text",
      "--ssq-color-warning-background",
      "--ssq-color-warning-border",
      "--ssq-color-warning-text",
      "--ssq-color-error-text"
    ]
  },
  radius: {
    qhdsSm: "12px",
    sm: "4px",
    md: "0.5rem"
  },
  space: {
    0: "0",
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    7: "2rem",
    8: "2.25rem",
    9: "2.5rem",
    10: "3rem",
    12: "4rem",
    16: "10rem"
  },
  typography: {
    fontFamilyBase: '"Noto Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    fontFamilyHeading: '"Noto Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    fontFamilySiteTitle: '"Noto Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    fontSizeBase: "1rem",
    fontWeightBold: 700,
    fontWeightRegular: 400,
    fontWeightSemibold: 600,
    h1Desktop: "3rem",
    h1DesktopLineHeight: "3.75rem",
    h1Mobile: "2rem",
    h1MobileLineHeight: "2.5rem",
    h2Desktop: "2rem",
    h2DesktopLineHeight: "2.5rem",
    h2Mobile: "1.75rem",
    h2MobileLineHeight: "2.25rem",
    h3: "1.5rem",
    h3LineHeight: "2rem",
    h4: "1.25rem",
    h4LineHeight: "1.5rem",
    h5: "1rem",
    h5LineHeight: "1.25rem",
    h6: "0.875rem",
    h6LineHeight: "1rem",
    leadDesktop: "1.5rem",
    leadMobile: "1.25rem",
    letterSpacingDefault: 0,
    lineHeightBase: 1.5,
    lineHeightParagraph: 1.75
  },
  layout: {
    contentBlockSpacingDesktop: "3rem",
    contentBlockSpacingMobile: "2rem",
    sectionPaddingDesktop: "4rem",
    sectionPaddingMobile: "2.25rem"
  },
  aivis: {
    color: {
      paletteVariables: [
        "--aivis-palette-page",
        "--aivis-palette-surface",
        "--aivis-palette-surface-muted",
        "--aivis-palette-surface-raised",
        "--aivis-palette-border",
        "--aivis-palette-border-muted",
        "--aivis-palette-border-soft",
        "--aivis-palette-text",
        "--aivis-palette-text-muted",
        "--aivis-palette-accent",
        "--aivis-palette-accent-strong",
        "--aivis-palette-accent-soft",
        "--aivis-palette-accent-soft-border",
        "--aivis-palette-success-text",
        "--aivis-palette-warning-text",
        "--aivis-palette-warning-surface"
      ],
      semanticVariables: [
        "--aivis-shell-page",
        "--aivis-shell-surface",
        "--aivis-shell-surface-muted",
        "--aivis-shell-border",
        "--aivis-shell-border-muted",
        "--aivis-shell-text",
        "--aivis-shell-muted",
        "--aivis-shell-accent",
        "--aivis-shell-accent-strong",
        "--aivis-shell-focus",
        "--aivis-shell-on-accent",
        "--aivis-shell-chip-background",
        "--aivis-shell-chip-border",
        "--aivis-color-card-surface",
        "--aivis-color-card-border",
        "--aivis-color-success-text",
        "--aivis-color-success-background",
        "--aivis-color-success-border",
        "--aivis-color-warning-text",
        "--aivis-color-warning-background",
        "--aivis-color-warning-border"
      ]
    },
    radiusVariables: [
      "--aivis-radius-sm",
      "--aivis-radius-md",
      "--aivis-radius-pill",
      "--aivis-shell-radius"
    ],
    spacingVariables: [
      "--aivis-space-0",
      "--aivis-space-1",
      "--aivis-space-2",
      "--aivis-space-3",
      "--aivis-space-4",
      "--aivis-space-5",
      "--aivis-space-6",
      "--aivis-space-7",
      "--aivis-space-9",
      "--aivis-space-10",
      "--aivis-workbench-section-gap",
      "--aivis-workbench-panel-gap",
      "--aivis-workbench-card-padding",
      "--aivis-shell-content-padding"
    ],
    typographyVariables: [
      "--aivis-font-size-eyebrow",
      "--aivis-font-size-small",
      "--aivis-font-size-caption",
      "--aivis-font-size-body-sm",
      "--aivis-font-size-panel-heading",
      "--aivis-font-size-title-fluid",
      "--aivis-font-weight-bold",
      "--aivis-font-weight-heavy",
      "--aivis-line-height-title",
      "--aivis-line-height-lead"
    ],
    layoutVariables: [
      "--aivis-shell-sidebar-columns",
      "--aivis-workbench-header-columns",
      "--aivis-workbench-context-columns",
      "--aivis-workbench-grid-columns",
      "--aivis-workbench-grid-columns-medium",
      "--aivis-workbench-summary-columns"
    ]
  }
} as const;
